name: mental_health_fitness_ui
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7
  sizer: ^2.0.15
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_animate: ^4.2.0+1
  percent_indicator: ^4.2.3
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/nav_bar_icons/
    - assets/fonts/

  fonts:
    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya-Black.ttf
          weight: 900
        - asset: assets/fonts/Alegreya-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Alegreya-Bold.ttf
          weight: 700
        - asset: assets/fonts/Alegreya-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Alegreya-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Alegreya-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Alegreya-Italic.ttf
          style: italic
        - asset: assets/fonts/Alegreya-Medium.ttf
          weight: 500
        - asset: assets/fonts/Alegreya-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Alegreya-Regular.ttf
          weight: 400
        - asset: assets/fonts/Alegreya-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Alegreya-SemiBoldItalic.ttf
          weight: 600
          style: italic

    - family: Alegreya Sans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Black.ttf
          weight: 900
        - asset: assets/fonts/AlegreyaSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlegreyaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/AlegreyaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlegreyaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/AlegreyaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/AlegreyaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/AlegreyaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/AlegreyaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/AlegreyaSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/AlegreyaSans-ThinItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/AlegreyaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/AlegreyaSans-LightItalic.ttf
          weight: 300
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/hf_ic.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/hf_ic.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/hf_ic.png

  android_12:
    color: "#ffffff"
    image: assets/images/hf_ic.png
    icon_background_color: "#ffffff"
