name: mental_health_fitness_ui
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7
  sizer: ^2.0.15
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_animate: ^4.2.0+1
  percent_indicator: ^4.2.3
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/nav_bar_icons/

  # fonts:
  #   - family: Alegreya
  #     fonts:
  #       - asset: fonts/Alegreya-Black.ttf
  #       - asset: fonts/Alegreya-BlackItalic.ttf
  #       - asset: fonts/Alegreya-Bold.ttf
  #       - asset: fonts/Alegreya-BoldItalic.ttf
  #       - asset: fonts/Alegreya-ExtraBold.ttf
  #       - asset: fonts/Alegreya-ExtraBoldItalic.ttf
  #       - asset: fonts/Alegreya-Italic-VariableFont_wght.ttf
  #       - asset: fonts/Alegreya-Italic.ttf
  #       - asset: fonts/Alegreya-Medium.ttf
  #       - asset: fonts/Alegreya-MediumItalic.ttf
  #       - asset: fonts/Alegreya-Regular.ttf
  #       - asset: fonts/Alegreya-SemiBold.ttf
  #       - asset: fonts/Alegreya-SemiBoldItalic.ttf
  #       - asset: fonts/Alegreya-VariableFont_wght.ttf

  #   - family: Alegreya Sans
  #     fonts:
  #       - asset: fonts/AlegreyaSans-Black.ttf
  #       - asset: fonts/AlegreyaSans-BlackItalic.ttf
  #       - asset: fonts/AlegreyaSans-Bold.ttf
  #       - asset: fonts/AlegreyaSans-BoldItalic.ttf
  #       - asset: fonts/AlegreyaSans-ExtraBold.ttf
  #       - asset: fonts/AlegreyaSans-ExtraBoldItalic.ttf
  #       - asset: fonts/AlegreyaSans-Italic.ttf
  #       - asset: fonts/AlegreyaSans-Medium.ttf
  #       - asset: fonts/AlegreyaSans-MediumItalic.ttf
  #       - asset: fonts/AlegreyaSans-Regular.ttf
  #       - asset: fonts/AlegreyaSans-Thin.ttf
  #       - asset: fonts/AlegreyaSans-ThinItalic.ttf
  #       - asset: fonts/AlegreyaSans-Light.ttf
  #       - asset: fonts/AlegreyaSans-LightItalic.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/hf_ic.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/hf_ic.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/hf_ic.png

  android_12:
    color: "#ffffff"
    image: assets/images/hf_ic.png
    icon_background_color: "#ffffff"
